# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/osconfig_v1/proto/osconfig_common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="google/cloud/osconfig_v1/proto/osconfig_common.proto",
    package="google.cloud.osconfig.v1",
    syntax="proto3",
    serialized_options=b"\n\034com.google.cloud.osconfig.v1B\006CommonZ@google.golang.org/genproto/googleapis/cloud/osconfig/v1;osconfig\252\002\030Google.Cloud.OsConfig.V1\312\002\030Google\\Cloud\\OsConfig\\V1\352\002\033Google::Cloud::OsConfig::V1",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n4google/cloud/osconfig_v1/proto/osconfig_common.proto\x12\x18google.cloud.osconfig.v1"<\n\x0e\x46ixedOrPercent\x12\x0f\n\x05\x66ixed\x18\x01 \x01(\x05H\x00\x12\x11\n\x07percent\x18\x02 \x01(\x05H\x00\x42\x06\n\x04modeB\xbc\x01\n\x1c\x63om.google.cloud.osconfig.v1B\x06\x43ommonZ@google.golang.org/genproto/googleapis/cloud/osconfig/v1;osconfig\xaa\x02\x18Google.Cloud.OsConfig.V1\xca\x02\x18Google\\Cloud\\OsConfig\\V1\xea\x02\x1bGoogle::Cloud::OsConfig::V1b\x06proto3',
)


_FIXEDORPERCENT = _descriptor.Descriptor(
    name="FixedOrPercent",
    full_name="google.cloud.osconfig.v1.FixedOrPercent",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="fixed",
            full_name="google.cloud.osconfig.v1.FixedOrPercent.fixed",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="percent",
            full_name="google.cloud.osconfig.v1.FixedOrPercent.percent",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="mode",
            full_name="google.cloud.osconfig.v1.FixedOrPercent.mode",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=82,
    serialized_end=142,
)

_FIXEDORPERCENT.oneofs_by_name["mode"].fields.append(
    _FIXEDORPERCENT.fields_by_name["fixed"]
)
_FIXEDORPERCENT.fields_by_name[
    "fixed"
].containing_oneof = _FIXEDORPERCENT.oneofs_by_name["mode"]
_FIXEDORPERCENT.oneofs_by_name["mode"].fields.append(
    _FIXEDORPERCENT.fields_by_name["percent"]
)
_FIXEDORPERCENT.fields_by_name[
    "percent"
].containing_oneof = _FIXEDORPERCENT.oneofs_by_name["mode"]
DESCRIPTOR.message_types_by_name["FixedOrPercent"] = _FIXEDORPERCENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FixedOrPercent = _reflection.GeneratedProtocolMessageType(
    "FixedOrPercent",
    (_message.Message,),
    {
        "DESCRIPTOR": _FIXEDORPERCENT,
        "__module__": "google.cloud.osconfig_v1.proto.osconfig_common_pb2",
        "__doc__": """Message encapsulating a value that can be either absolute (“fixed”) or
  relative (“percent”) to a value.
  
  Attributes:
      mode:
          Type of the value.
      fixed:
          Specifies a fixed value.
      percent:
          Specifies the relative value defined as a percentage, which
          will be multiplied by a reference value.
  """,
        # @@protoc_insertion_point(class_scope:google.cloud.osconfig.v1.FixedOrPercent)
    },
)
_sym_db.RegisterMessage(FixedOrPercent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
