# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.cloud.osconfig_v1.proto import (
    patch_deployments_pb2 as google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2,
)
from google.cloud.osconfig_v1.proto import (
    patch_jobs_pb2 as google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2,
)
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class OsConfigServiceStub(object):
    """OS Config API

    The OS Config service is a server-side component that you can use to
    manage package installations and patch jobs for virtual machine instances.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutePatchJob = channel.unary_unary(
            "/google.cloud.osconfig.v1.OsConfigService/ExecutePatchJob",
            request_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ExecutePatchJobRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.PatchJob.FromString,
        )
        self.GetPatchJob = channel.unary_unary(
            "/google.cloud.osconfig.v1.OsConfigService/GetPatchJob",
            request_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.GetPatchJobRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.PatchJob.FromString,
        )
        self.CancelPatchJob = channel.unary_unary(
            "/google.cloud.osconfig.v1.OsConfigService/CancelPatchJob",
            request_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.CancelPatchJobRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.PatchJob.FromString,
        )
        self.ListPatchJobs = channel.unary_unary(
            "/google.cloud.osconfig.v1.OsConfigService/ListPatchJobs",
            request_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ListPatchJobsRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ListPatchJobsResponse.FromString,
        )
        self.ListPatchJobInstanceDetails = channel.unary_unary(
            "/google.cloud.osconfig.v1.OsConfigService/ListPatchJobInstanceDetails",
            request_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ListPatchJobInstanceDetailsRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ListPatchJobInstanceDetailsResponse.FromString,
        )
        self.CreatePatchDeployment = channel.unary_unary(
            "/google.cloud.osconfig.v1.OsConfigService/CreatePatchDeployment",
            request_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.CreatePatchDeploymentRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.PatchDeployment.FromString,
        )
        self.GetPatchDeployment = channel.unary_unary(
            "/google.cloud.osconfig.v1.OsConfigService/GetPatchDeployment",
            request_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.GetPatchDeploymentRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.PatchDeployment.FromString,
        )
        self.ListPatchDeployments = channel.unary_unary(
            "/google.cloud.osconfig.v1.OsConfigService/ListPatchDeployments",
            request_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.ListPatchDeploymentsRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.ListPatchDeploymentsResponse.FromString,
        )
        self.DeletePatchDeployment = channel.unary_unary(
            "/google.cloud.osconfig.v1.OsConfigService/DeletePatchDeployment",
            request_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.DeletePatchDeploymentRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class OsConfigServiceServicer(object):
    """OS Config API

    The OS Config service is a server-side component that you can use to
    manage package installations and patch jobs for virtual machine instances.
    """

    def ExecutePatchJob(self, request, context):
        """Patch VM instances by creating and running a patch job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPatchJob(self, request, context):
        """Get the patch job. This can be used to track the progress of an
        ongoing patch job or review the details of completed jobs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelPatchJob(self, request, context):
        """Cancel a patch job. The patch job must be active. Canceled patch jobs
        cannot be restarted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPatchJobs(self, request, context):
        """Get a list of patch jobs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPatchJobInstanceDetails(self, request, context):
        """Get a list of instance details for a given patch job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreatePatchDeployment(self, request, context):
        """Create an OS Config patch deployment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPatchDeployment(self, request, context):
        """Get an OS Config patch deployment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPatchDeployments(self, request, context):
        """Get a page of OS Config patch deployments.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeletePatchDeployment(self, request, context):
        """Delete an OS Config patch deployment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OsConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecutePatchJob": grpc.unary_unary_rpc_method_handler(
            servicer.ExecutePatchJob,
            request_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ExecutePatchJobRequest.FromString,
            response_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.PatchJob.SerializeToString,
        ),
        "GetPatchJob": grpc.unary_unary_rpc_method_handler(
            servicer.GetPatchJob,
            request_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.GetPatchJobRequest.FromString,
            response_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.PatchJob.SerializeToString,
        ),
        "CancelPatchJob": grpc.unary_unary_rpc_method_handler(
            servicer.CancelPatchJob,
            request_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.CancelPatchJobRequest.FromString,
            response_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.PatchJob.SerializeToString,
        ),
        "ListPatchJobs": grpc.unary_unary_rpc_method_handler(
            servicer.ListPatchJobs,
            request_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ListPatchJobsRequest.FromString,
            response_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ListPatchJobsResponse.SerializeToString,
        ),
        "ListPatchJobInstanceDetails": grpc.unary_unary_rpc_method_handler(
            servicer.ListPatchJobInstanceDetails,
            request_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ListPatchJobInstanceDetailsRequest.FromString,
            response_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ListPatchJobInstanceDetailsResponse.SerializeToString,
        ),
        "CreatePatchDeployment": grpc.unary_unary_rpc_method_handler(
            servicer.CreatePatchDeployment,
            request_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.CreatePatchDeploymentRequest.FromString,
            response_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.PatchDeployment.SerializeToString,
        ),
        "GetPatchDeployment": grpc.unary_unary_rpc_method_handler(
            servicer.GetPatchDeployment,
            request_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.GetPatchDeploymentRequest.FromString,
            response_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.PatchDeployment.SerializeToString,
        ),
        "ListPatchDeployments": grpc.unary_unary_rpc_method_handler(
            servicer.ListPatchDeployments,
            request_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.ListPatchDeploymentsRequest.FromString,
            response_serializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.ListPatchDeploymentsResponse.SerializeToString,
        ),
        "DeletePatchDeployment": grpc.unary_unary_rpc_method_handler(
            servicer.DeletePatchDeployment,
            request_deserializer=google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.DeletePatchDeploymentRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "google.cloud.osconfig.v1.OsConfigService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class OsConfigService(object):
    """OS Config API

    The OS Config service is a server-side component that you can use to
    manage package installations and patch jobs for virtual machine instances.
    """

    @staticmethod
    def ExecutePatchJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.osconfig.v1.OsConfigService/ExecutePatchJob",
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ExecutePatchJobRequest.SerializeToString,
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.PatchJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetPatchJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.osconfig.v1.OsConfigService/GetPatchJob",
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.GetPatchJobRequest.SerializeToString,
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.PatchJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CancelPatchJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.osconfig.v1.OsConfigService/CancelPatchJob",
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.CancelPatchJobRequest.SerializeToString,
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.PatchJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListPatchJobs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.osconfig.v1.OsConfigService/ListPatchJobs",
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ListPatchJobsRequest.SerializeToString,
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ListPatchJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListPatchJobInstanceDetails(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.osconfig.v1.OsConfigService/ListPatchJobInstanceDetails",
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ListPatchJobInstanceDetailsRequest.SerializeToString,
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__jobs__pb2.ListPatchJobInstanceDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CreatePatchDeployment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.osconfig.v1.OsConfigService/CreatePatchDeployment",
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.CreatePatchDeploymentRequest.SerializeToString,
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.PatchDeployment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetPatchDeployment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.osconfig.v1.OsConfigService/GetPatchDeployment",
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.GetPatchDeploymentRequest.SerializeToString,
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.PatchDeployment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListPatchDeployments(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.osconfig.v1.OsConfigService/ListPatchDeployments",
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.ListPatchDeploymentsRequest.SerializeToString,
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.ListPatchDeploymentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeletePatchDeployment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.osconfig.v1.OsConfigService/DeletePatchDeployment",
            google_dot_cloud_dot_osconfig__v1_dot_proto_dot_patch__deployments__pb2.DeletePatchDeploymentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
